### ISSUE TITLE
Digipeat REGEN

### ISSUE THREAD

**Issue by na7q** [wb2osz/direwolf#105]
Does Direwolf have the ability to digipeat a packet exactly as it's heard?
So not tracing, or marking digipeated packets, but repeating it as it's heard, as if it's from the originating station like with using the REGEN option.

I need to use a portable digi in a location that has no internet, only digipeaters that do not digipeat an already digipeated station. My purpose in a sense is to bypass this, by directly repeating what my filtered portable digi picks up. Has to do with filling in some large places when out in the backcountry where being picked up just isn't possible by any currently installed digis.

Could this option be implemented? Or have the code easily be modified with REGEN? As it does everything needed to accomplish this, except it doesn't follow the rules of the config file.

**Comment by na7q** [comment]
The REGEN replacement of DIGIPEAT does what I need, however it does not follow any filters, or anything in the config file. So still a bust.

**Comment by craigerl** [comment]
you can look into REGEN, but with no "REGENFILTER" implemented it would get out of control really fast.  I agree with your feature Idea.  I have a portable that is completely deaf to the world and the only thing it can hear is my digipeater.  It's ultimately useless when the internet goes out.    The digipeater hears the message replies that are supposed to go to my portal, and does nothing to get them there.

**Comment by craigerl** [comment]
maybe a REGEN that puts NORF or NOGATE or something in the header to make sure there is never an infinite feedback loop?  i cloned the source, but the solution wasnt obvious.   regenerating packets for a specific callsign inside the packet data would be a killer feature for me in the mountains where ht radios are otherwise useless.  a regen would allow my ht to leverage the big digipeater antenna.

**Comment by na7q** [comment]
Still seems there is a small bit of demand for this feature. I'm wondering if the filtering functions will be supported with this at some point? Such as DEDUPE.

**Comment by wb2osz** [comment]
See User Guide, "Frame Regeneration" section.
Use this cautiously only for special situations.  Retransmitting on the same frequency would be a bad idea.  If two people did this, a packet could bounce back and forth between them forever.
Closing.
