### ISSUE TITLE
Text and window color preferences don't stick

### ISSUE THREAD

**Issue by madsci77** [wb2osz/direwolf#108]
Running 1.4 in Windows 8.1.  The default text colors include bright green on white for the packet payload, making it almost impossible to read, at least on my screen.

Changing the colors in the preferences doesn't work.  If the background is changed, only the text already on the screen changes.  As soon as more appears, it reverts to the old color scheme.

![screenshot 2017-08-03 11 58 37](https://user-images.githubusercontent.com/22358906/28938558-44132098-7843-11e7-8e51-6cd6b3323f21.png)

**Comment by wb2osz** [comment]
Text colors had a major overhaul in the "dev" version.  Light green has been replaced by dark green so it is easier to read.  More improvements for the Linux version.  Give it a try and let me know what you think.

**Comment by wb2osz** [comment]
Text colors had a major overhaul in the "dev" version. Light green has been replaced by dark green so it is easier to read. More improvements for the Linux version. Give it a try and let me know what you think.
