### ISSUE TITLE
Tickler - move APPLE ifdef in direwolf.h

### ISSUE THREAD

**Issue by rlevine** [wb2osz/direwolf#113]
(I'm putting this here so the change doesn't get lost.)

In direwolf.h, the __APPLE__ define has to be after:

   #include <pthread.h>

(Line 130 in the file, before this change.)

pthread.h pulls in <sys/cdefs.h>, which redefines __DARWIN_C_LEVEL back to ansi, which breaks things.

Diff for the corrected file, against 7247099:

➜  direwolf git:(dev) ✗ diff direwolf_7247099.h direwolf.h
34,46d33
<
< #ifdef __APPLE__
<
< // https://groups.yahoo.com/neo/groups/direwolf_packet/conversations/messages/2072
<
< // I think we should put it here, so it will apply to all files,
< // rather than only in ptt.c.
<
< #define __DARWIN_C_LEVEL  __DARWIN_C_FULL
<
< #endif
<
<
132a120,130
> #ifdef __APPLE__
>
> // https://groups.yahoo.com/neo/groups/direwolf_packet/conversations/messages/2072
>
> // I think we should put it here, so it will apply to all files,
> // rather than only in ptt.c.
>
> #define __DARWIN_C_LEVEL  __DARWIN_C_FULL
>
> #endif
>

**Comment by wb2osz** [comment]
Added to "dev" branch.
 5cb6e04c54c628022ab044508bbbce414ce086f6
Thanks for your help with the Mac version.
