### ISSUE TITLE
2-digit ADEVICE error

### ISSUE THREAD

**Issue by tailstrikes** [wb2osz/direwolf#116]
When configuring any audio device >9 with ADEVICE, DireWolf [on Windows7] will throw an error '## doesnt match any of the output devices' reading the config on startup. Only workaround is to disable all currently not used audio devices - in hopes to bring the desired one to be listed among the first 9.

**Comment by wb2osz** [comment]
590c82b0402632ada23504a0c5673f7ad4588639
Fixed in "dev" branch and will appear in version 1.5.
