### ISSUE TITLE
Compling warnings with gcc 7.2.1 20170915

### ISSUE THREAD

**Issue by DwaineGarden** [wb2osz/direwolf#123]
Getting the following warnings when compiling direwolf dev branch with gcc v

mheard.c: In function ‘mheard_dump’:
mheard.c:210:24: warning: ‘%02d’ directive writing between 2 and 9 bytes into a region of size between 8 and 11 [-Wformat-overflow=]
  sprintf (result, "%4d:%02d", h, m);
                        ^~~~
mheard.c:210:19: note: directive argument in the range [-71582774, 71582774]
  sprintf (result, "%4d:%02d", h, m);
                   ^~~~~~~~~~
mheard.c:210:2: note: ‘sprintf’ output between 8 and 18 bytes into a destination of size 16
  sprintf (result, "%4d:%02d", h, m);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mheard.c:210:24: warning: ‘%02d’ directive writing between 2 and 9 bytes into a region of size between 8 and 11 [-Wformat-overflow=]
  sprintf (result, "%4d:%02d", h, m);
                        ^~~~
mheard.c:210:19: note: directive argument in the range [-71582774, 71582774]
  sprintf (result, "%4d:%02d", h, m);
                   ^~~~~~~~~~
mheard.c:210:2: note: ‘sprintf’ output between 8 and 18 bytes into a destination of size 16
  sprintf (result, "%4d:%02d", h, m);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by wb2osz** [comment]
This was probably fixed.
I don't see it with gcc 7.4.0.
