### ISSUE TITLE
User-configurable NMEA GPS baud rate

### ISSUE THREAD

**Issue by sq2mo** [wb2osz/direwolf#125]
I would like to request the option to change baudrate for NMEA GPS.
Currently rate it is hardcoded to 4800:
`s_gpsnmea_port_fd = serial_port_open (pconfig->gpsnmea_port, 4800);`
AFAIK, most GPS modules use 9600 nowadays.

**Comment by Luceoria** [comment]
Any plans to implement this option?

**Comment by sq2mo** [comment]
The option seems to be present in dev branch now, so closing.
