### ISSUE TITLE
Why can't direwolf use the default audio chip of the raspberry Pi ?

### ISSUE THREAD

**Issue by vallettea** [wb2osz/direwolf#137]
In order to only decode afsk ?
If it is possible what should i put in direwolf.conf ?

best

**Comment by na7q** [comment]
For starters, github is for bugs and issues with Direwolf. Questions should be asked in the Yahoo group. https://groups.yahoo.com/neo/groups/direwolf_packet/conversations/topics
As for the Pi, it supports outgoing audio. It was not built for input audio, hence the need for a sound card.

**Comment by vallettea** [comment]
yes but if I want to use direwolf only to decode ?

**Comment by na7q** [comment]
Then you need to buy a sound card.
