### ISSUE TITLE
Igate issue with digirepeating

### ISSUE THREAD

**Issue by drtechga** [wb2osz/direwolf#139]
It will not Igate when running on an odroid. It is just digirepeating everything. I have enabled IGate and it shows it verified, but does not send any data.

**Comment by dranch** [comment]
There is nothing special about an Odroid vs any other ARM SBC.  It's most likely a configuration issue that's stopping your Igate issue.  Please close this Git issue and re-post your question at  direwolf_packet@yahoogroups.com
