### ISSUE TITLE
Audio input device 0 error: File descriptor in bad state

### ISSUE THREAD

**Issue by Joshwaa2010** [wb2osz/direwolf#142]
I am a bit of a linux noob, sorry.  I can not figure out this issue.  I am not even sure it is a problem with direwolf.  

![direwolf](https://user-images.githubusercontent.com/26224063/39267065-c25a7f42-4899-11e8-9d2c-5ad3c9c25752.png)
![kern-log](https://user-images.githubusercontent.com/26224063/39267066-c2695224-4899-11e8-8d89-384e2dc84216.png)
![messages](https://user-images.githubusercontent.com/26224063/39267067-c2769754-4899-11e8-9329-043ceb18f781.png)

Running off a 5V 2.5A power supply. Raspberry Pi 3 B+, Latest Stretch, CMedia USB audio device connected directly to Pi USB.  Tried with Kenwood TH-D74A and Beofeng BF-F8HP with same results.

**Comment by dranch** [comment]
This direwolf github issue system is for reporting bugs or enhancement requests.  Please close this issue and report this same issue to the Direwolf Yahoo group at direwolf_packet@yahoogroups.com.  With that said, you're USB sound card is getting reset for either a possible low power issue or an RFI issue.  In your email to the Yahoo group, please provide your Direwolf config, your specific USB sound card you're using, and tell us about your setup (how you're wired the various parts together, etc).

--David
KI6ZHD

**Comment by wb2osz** [comment]
As David said, this is not the right place to ask for debugging help.  This is for tracking software defects and enhancement requests.  

From the system log, the USB audio device is messed up and resetting.  David had good suggestions:  maybe transmit RF is getting into the USB audio adapter.  Try disabling transmit and see if it receives OK for a while.  Low voltage can also be an issue.  Even if you have a hefty power supply, there might be too much voltage drop with a cheap USB cable.  Get a voltmeter and measure the supply voltage on the RPi.

**Comment by na7q** [comment]
I'd suggest a Fe Pi sound card. It goes on the gpio pins and works a hundred times better. Every USB sound card I've had will present this issue. On all versions of the Pi. Since I got the Fe Pi card, I've never had issues with RF killing the sound.

**Comment by wb2osz** [comment]
This is not a discussion group.  The "issues" section is for tracking software bugs and enhancement requests.  Please take general discussions to https://groups.yahoo.com/neo/groups/direwolf_packet/info
Most people probably never heard of the "Fe Pi."   I'm sure they would be interested in knowing about this alternative to the USB audio adapter.  It would be especially useful for the Pi zero which has a single USB port that you might need for something else.

**Comment by Joshwaa2010** [comment]
Thanks for the info.  Also thanks for a working link for the group.
