### ISSUE TITLE
Feature Request: APRS Messenger Compatible Beaconing 

### ISSUE THREAD

**Issue by radar27** [wb2osz/direwolf#145]
Greetings,

I have been using Direwolf on a Raspberry Pi Zero as a mobile tracker for some time with great success on both 2m and 30m using standard AFSK.  One thing that I thought might be a useful enhancement would be the ability to add other modes to the beacon for HF operations.  Today I just run 300 baud AFSK on 30m which largely works, but other developments have been made to allow the APRS protocol to use other transports which are more immune to conditions which can be present at HF.  

http://www.crosscountrywireless.net/aprs_messenger.htm

More details on using the other protocols are here:

http://www.crosscountrywireless.net/APRS%20over%20PSK-63%20-%20How%20it%20works.txt

At the moment the only way I know how to get these additional modes is to run APRS Messenger on an x86 type system.  Ideally I was hoping it would be possible to add modes to Direwolf itself, to allow multiple protocol beaconing.  Today with APRS Messenger, you can select AX.25 (classic AFSK) and then one other mode.  When it is time to beacon, one mode will transmit, then a pause, then the other.  The goal there is to cover "both bases", letting the classic AFSK beacon go for any other systems which are set to decode it (if signal strengths are sufficient) as well as the newer (MFSK/GMSK/PSK) mode(s) for stations running APRS Messenger (or a future version of Direwolf!), allowing for a decode if conditions are not strong enough for AFSK alone.  This would greatly enhance capabilities for APRS operations on HF where that signals are marginal.

73!

**Comment by wb2osz** [comment]
http://www.crosscountrywireless.net/aprs_messenger.htm  says  "The APRS Messenger program is now obsolete. It now has problems running on Windows 10 and as we cannot load the programming sofware on a Windows 10 machine we cannot do any more development work on it."

Dire Wolf now has FX.25 Forward Error Correction which allows usage of AX.25 over very poor radio conditions.  

Please reopen the case, or create a new one if you want to continue discussing this.
