### ISSUE TITLE
 Xastir and Soundmodem with Raspberry Pi3 B  Debian Linux Setup....

### ISSUE THREAD

**Issue by catsilver** [wb2osz/direwolf#146]
Hello,
I'm trying Xastir and Soundmodem to make an APRS digipeater, on the Raspberry PI3 with Linux Debian software, can you please kindly explain the settings to make it work perfectly, or any suggestions?

thanks....

**Comment by wb2osz** [comment]
This "issues" area is for reporting defects in the "Dire Wolf" software and making enhancement requests.  It is not a discussion group.  The Dire Wolf documentation can be found here:   https://github.com/wb2osz/direwolf/tree/dev/doc 

There are two different applications known as "soundmodem."   One of them is part of the AX.25 for Linux package.   The other is from UZ7HO.  

The Xastir documentation is here:  http://xastir.org/index.php/Main_Page
