### ISSUE TITLE
Absolute Newbie with a question

### ISSUE THREAD

**Issue by froboz99** [wb2osz/direwolf#15]
First attempt to use this code from source. Windows 10 Pro 64 bit environment. Fresh load of the MinGW components etc, 

make -f Makefile.win           succeeds.

execution of newly created direwolf.exe crashes. gdb error message is:
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 824.0xda4]
0x0045bd07 in convolve (filter_size=156, filter=0x47d420 <demodulator_state+96>, data=0x47ed20 <demodulator_state+6496>)
    at demod_afsk.c:117
117                 sum += f[j] * d[j];
(gdb)

Any suggestions most welcome:

73
KD6CWF
Terry

**Comment by wb2osz** [comment]
That source code line looks like version 1.2.  The problematic section was removed on Dec. 26 in 1.3 dev snapshot I.
