### ISSUE TITLE
Compile problem on OSX  (v10.13.5)

### ISSUE THREAD

**Issue by sm3ulc** [wb2osz/direwolf#158]
Being a bit novice on pulling:

git clone https://github.com/wb2osz/direwolf
cd direwolf
git checkout dev
make

...
find: /Developer/SDKs: No such file or directory

=> Do not use any SDK
    igate.c:1280:15: error: use of undeclared identifier 'MSG_NOSIGNAL'
    err = SOCK_SEND (igate_sock, stemp, stemp_len);
    ^
    ./direwolf.h:259:50: note: expanded from macro 'SOCK_SEND'
    #define SOCK_SEND(s,data,size) send(s,data,size, MSG_NOSIGNAL)
    ^
    1 error generated.
    make: *** [igate.o] Error 1

**Comment by wb2osz** [comment]
Did you read chapter 6 of the User Guide?   Mac OSX is a lot more complicated than Linux.

**Comment by nateberkopec** [comment]
I'm having the same issue on 1.5-beta4. I would think that #140 would have addressed this.

**Comment by nateberkopec** [comment]
OK, this particular error is fixed on `dev` - it just didn't make the beta4 release.

**Comment by darksidelemm** [comment]
So I have found the following (using the dev branch):

A) The select_sdk.sh script will sit on the 'Please select a number' prompt for a while *before* it gives you the options to select. Yes, it says 'wait for results', but it immediately then goes 'enter the number', which is a bit confusing.

B) The select_sdk.sh script can quite happily find nothing (i.e. 'Do not use any SDK', option 1), and the build can still progress just fine (given that Macports / Homebrew provide everything that is required anyway...)

C) The Makefile.macosx file needs to be edited manually in two places (even though the variable name 'INSTALLDIR' is the same) to switch from looking in /usr/local/ to /opt/local/ if you are using Macports. If you only edit the first INSTALLDIR entry, it will get halfway through compilation and fail at the linking step. 

None of the above are clear in chapter 6 of the user guide, and lead to much frustration! When running distributions like Macports or Homebrew, building on MacOSX is *not* that much more complicated than on Linux. All the same things are available, just sometimes in slightly different places...

**Comment by wb2osz** [comment]
The build procedure now uses cmake.  Makefile.macosx no longer exists in the dev branch.  Please try using the new procedure with cmake.

**Comment by darksidelemm** [comment]
Yep, Direwolf builds just fine under OSX using cmake, with the dependencies supplied via Macports. Thanks!
