### ISSUE TITLE
Document TimeStamp Format

### ISSUE THREAD

**Issue by nayrnet** [wb2osz/direwolf#160]
I cannot for the life of me figure out what -T CLI option expects me to provide.. it takes my input literally and logs packets with HH:MM:SS instead of any actual time.

```[0.3 HH:MM:SS] N1RNR-9>SXUWTR,WIDE1-1,KC0D,WIDE2*:`pL'q\4j/`"I`}146.460MHz CO4X4RNR SAR-ES TEAM_%<0x0d>```

**Comment by wb2osz** [comment]
Thanks for the feedback.  Look in the User Guide, sections 9.16  and 14.6.4.  Does this answer your question or does the documentation need to be improved?

**Comment by nayrnet** [comment]
Ah man I'm an idiot, I've been running code out of dev but reading docs out of master.. that explains why alot of what I was seeing was not documented lol.. Yes that is exactly what I was looking for.
