### ISSUE TITLE
gpsd configuration file?

### ISSUE THREAD

**Issue by Stuart-G3SNA** [wb2osz/direwolf#173]
Final details regarding setting TBEACON params refers to a configuration file.  What is the filename please?

**Comment by Stuart-G3SNA** [comment]
I'm referring to section 6 Configuring Beaconing

![config_clip](https://user-images.githubusercontent.com/25826077/46903419-651f4b00-cecc-11e8-97d4-02a633b07e93.jpg)

**Comment by meinja** [comment]
Hi Stuart,
Look for the file "direwolf.conf".
73 KP3FT

**Comment by Stuart-G3SNA** [comment]
Thanks.  Should have know that but didn't see it when I searched.  Cheers, Stuart G3SNA

**Comment by Stuart-G3SNA** [comment]
Thanks David.  I did find that myself and I am experimenting with things.  73 Stuart
