### ISSUE TITLE
Ptt with audio signal

### ISSUE THREAD

**Issue by Skinoku** [wb2osz/direwolf#174]
Dear wb2osz,
thank you for the effort developing this exceptional software. I really like it.
I was thinking if it was possible to generate a tone on a determinate audio interface for using it like PTT signal instead of GPIO or serial flow control?
Cheers!

**Comment by wb2osz** [comment]
I don't understand.  You can use a VOX circuit that activates PTT when the transmit audio is present.  This is discussed in the User Guide.
