### ISSUE TITLE
Developper documentation missing

### ISSUE THREAD

**Issue by F5OEO** [wb2osz/direwolf#178]
Not an issue, but instead of inspecting all sources,  I like to integrate output of symbols to transmit FSK with https://github.com/F5OEO/rpitx/tree/v2beta
Any help appreciate to point how the best way to interface.

**Comment by wb2osz** [comment]
Please contact me directly to discuss possibilities.   wb2osz  <at>  comcast  <dot>  net

**Comment by wb2osz** [comment]
Please contact me directly to discuss possibilities. wb2osz comcast net
