### ISSUE TITLE
Can Direwolf jump into 14400 or 19200 baud rates

### ISSUE THREAD

**Issue by pavelmc** [wb2osz/direwolf#18]
We in Camagüey, Cuba use Direwolf as a software modem to maintain a 2m VHF radio packet network using full TCP/IP protocol. 

This network is used as a very cheap alternative to connect to our international email provided by our ham radio association. (Internet here is $2 USD/hour, that is about a mean monthly salary for one full day of connectivity)

We will love to see a version of direwolf implementing a faster FSK modem, let's say 14400 or 19200 baud rate ones.

Can this be done?

We have plenty of BW allowed for this in the 70cm band spectrum (Digital Data max BW is about 30 Khz in 2m and 150 Khz in 70 cm bands)

We know that this can need modified radios, but that's not a problem, as we use dedicated hardware in each network node.

73, CO7WT.

**Comment by wb2osz** [comment]
The version in the "dev" branch can go much higher than 9600.   See new document  Going-beyond-9600-baud.pdf  in the doc directory.
