### ISSUE TITLE
MicroModem performance figure in WA8LMF-TNC-Test-CD-Results.pdf is wrong

### ISSUE THREAD

**Issue by markqvist** [wb2osz/direwolf#187]
The demodulated package count for MicroModem in the WA8LMF-TNC-Test-CD-Results.pdf document is wrong.

I can understand the confusion, but the number you got seems to be pulled from a user comment on one of the pages at my website. He is referring to an DIY breadboard version he built himself.

I just ran a few passes and MicroModem decodes 905 packets from track 1 of the test CD.

I hope you'll update your figure, cause frankly 658 packets makes my modem look like a piece of junk.

**Comment by wb2osz** [comment]
Thanks for providing more dependable information.
This has been updated in the 'dev' branch.
