### ISSUE TITLE
txt. File to add data to comment line in P beacon 

### ISSUE THREAD

**Issue by hellfireglass** [wb2osz/direwolf#197]
I’m looking for a way to automatically copy text from a txt. file and add it to a comment line of a beacon. The .txt file will be created and updated by another program. 

Thanks for any help,
Dave

**Comment by wb2osz** [comment]
The Issues section is for reporting defects in the software and requesting new features.   It is for tracking possible software modifications, not general discussions.

General discussions should go to the discussion group.  

Read the documentation for Beacons in the User Guide.  There is an option to do this.
