### ISSUE TITLE
Font color similar to background

### ISSUE THREAD

**Issue by DL7AD** [wb2osz/direwolf#2]
On Linux the background color on terminals is almost the same than the colors used for the fonts which makes it unreadable.
![bug_direwolf](https://cloud.githubusercontent.com/assets/5694705/9559213/23e9a37a-4df0-11e5-8455-ef761a330135.png)

**Comment by wb2osz** [comment]
A work-around is to use the "-t 0" command line option to disable text color.

See comments in textcolor.c for more discussion of this issue.

**Comment by cniesen** [comment]
FYI, I encountered the same issue, wanting the multiple colors but a black background.
Since I was building from the source I swapped the color code of black and white in the `textcolor.c` file.  Looks nice now.

**Comment by ko6kL** [comment]
-t o 
on the command line worked , thank you , the light green on white was killing me....
right click icon make property like this...
C:\DownLoads-\ham-programs\direwolf\direwolf-1.5-beta2-win\direwolf.exe -t 0

a larger box would be nice to keep things on one line ???

**Comment by wb2osz** [comment]
Text color handling had a major overhaul in the "dev" branch in preparation for release 1.6.  it now works better with more terminal types.   Please give it a try and let me know how it works for you.

**Comment by ko6kL** [comment]
have the colorsstart up text on the HF window ( top_) bottom in 2m window.

file attached.

     On Saturday, July 6, 2019, 5:30:06 PM PDT, wb2osz <notifications@github.com> wrote:  
 
 
Text color handling had a major overhaul in the "dev" branch in preparation for release 1.6. it now works better with more terminal types. Please give it a try and let me know how it works for you.

**Comment by Tim-VK3MIT** [comment]
> A work-around is to use the "-t 0" command line option to disable text color.
> 
> See comments in textcolor.c for more discussion of this issue.

How do i use the "-t 0" switch in the windows version of Direwolf (the text colours on the screen are a problem) 

I've tried modifying the direwolf.exe filename to include the switch as previously suggested, but windows then doesn't know how to handle the file. Where am I going wrong please?

Thank you - Tim.

**Comment by wb2osz** [comment]
The "issues" section is for reporting software bugs and making new feature requests.
It is not a support forum for questions.  Please send questions to the discussion group.
https://groups.io/g/direwolf
