### ISSUE TITLE
TBEACON frames not copied to TCP KISS

### ISSUE THREAD

**Issue by AlyBadawy** [wb2osz/direwolf#203]
Not sure if this is a bug or was done intentionally, but the beacons generated by the Direwolf configuration file, are not copies on the TNC KISS port. all other beacons (from TCP KISS) are sent to audio, and all other received on audio are copied to the TCP KISS port. 

The reason why I am asking, is I am using another software (APRX) as the core of the aprs engine, and direwolf as a KISS TNC. however, I need to beacon the location based on GPS from direwolf. this happens on the audio side, out to radio and then to RF. I am still interested in i-gating that beacon via the internet through APRX. 

Ideas?

**Comment by wb2osz** [comment]
Look in the User Guide, Beaconing section, "SENDTO" option.
You can use "R" and a number to simulate reception from the specified channel.
This is sent to the attached applications (KISS or AGW network interface) as if they were received over the radio.

**Comment by AlyBadawy** [comment]
Perfect. Exactly what I needed. Thanks a lot.
