### ISSUE TITLE
GPSD timeout

### ISSUE THREAD

**Issue by EvanVS** [wb2osz/direwolf#209]
when I run direwolf I get this message "GPSD: Timeout waiting for GPS data." I have troubleshooted the GPSD. I did everything right I think. When I run "cat /dev/ttyACM0" I see data. But when I run "xgps" There is no data. What could be going wrong? 

I cant find this file:
ect/default/gpsd

I Tried this but no luck:
http://www.catb.org/gpsd/troubleshooting.html

Here is the gps Im using:
https://www.amazon.com/gp/product/B078Y52FGQ/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

**Comment by jongross** [comment]
Hey @MrCre8ive,

In my limited experience, this means that gpsd isn't getting data from the gps, this isn't a direwolf issue.  If you run xgps (or cgps) and there is no fix data, then you need to make sure that the gps is feeding gpsd before troubleshooting further.

**Comment by wb2osz** [comment]
Release 1.6 has caught up with all the latest API changes for libgps.
It should be fine now.  Reopen the case if you are still having a problem.
