### ISSUE TITLE
ptrdiff_t’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by DwaineGarden** [wb2osz/direwolf#237]
Getting the following error when compiling the latest from the top of dev branch.

Scanning dependencies of target kissutil
[  8%] Building C object src/CMakeFiles/kissutil.dir/kissutil.c.o
/usr/src/direwolf/src/kissutil.c: In function ‘main’:
/usr/src/direwolf/src/kissutil.c:299:65: error: ‘ptrdiff_t’ undeclared (first use in this function)
    e = pthread_create (&tnc_tid, NULL, tnc_listen_net, (void *)(ptrdiff_t)99);

**Comment by dranch** [comment]
We need more details here.  What kind of computer, what OS, OS version, which compiler version, etc ?

**Comment by wb2osz** [comment]
This has been fixed in the dev branch.
