### ISSUE TITLE
FX.25 support

### ISSUE THREAD

**Issue by svancau** [wb2osz/direwolf#238]
Hello,

I tought it would be a nice experiment to add FEC (forward error correction) to APRS frames at digipeat.
Modifying hdlc_send and the input of hdlc_deframing seems to me to be the easiest route.
FX.25 only adds some bytes but the frame can still be decoded by any AX25 equipment
[spec](http://www.stensat.org/docs/FX-25_01_06.pdf)
Does it seem to be a good approach ?

Cheers,
Sébastien

**Comment by wb2osz** [comment]
This has been added in the "dev" branch.
