### ISSUE TITLE
Make CM108 PTT support for Linux *only* clearer

### ISSUE THREAD

**Issue by dranch** [wb2osz/direwolf#244]
In the bottom of the User-Guide section 9.2.9.5, it says:
--
This available only for Linux. It is an optional feature, selected at build time. If for some reason, your operating system does not have the necessary support, you can exclude this functionality by hacking Makefile.linux. There are comments explaining how to do this.
--

This Linux-only support should also be mentioned in the earlier 5.2.4 section.  This also should be updated a bit for the 1.6-DEV release to mention Cmake instead of Makefile.linux

**Comment by wb2osz** [comment]
This has been clarified in the next version of the User Guide.
Thanks for the feedback.
