### ISSUE TITLE
Direwolf Github readme.md has wrong character in build instructions

### ISSUE THREAD

**Issue by dranch** [wb2osz/direwolf#245]
The dash in the readme.md documentation in the line "make -j4" is the wrong character (it's a unicode) character but make expects a "dash" ASCII character.  This is tripping up users.

**Comment by wb2osz** [comment]
Fixed.
It was caused by a copy-n-paste from a different document.
Here is a handy way to find non-ASCII characters:
 grep --color='auto' -P -n "[^\x00-\x7f]" README.md
