### ISSUE TITLE
Height off by 10 on Beacon

### ISSUE THREAD

**Issue by wcravens** [wb2osz/direwolf#248]
I configured the following beacon...
PBEACON delay=1 every=30 overlay=S symbol="House QTH" lat##^07.389N long=##^18.759W power=50 height=30 gain=8.3 comment="" via=WIDE2-1

But when it goes out on the air the height is reported as 40.  At first I thought it was just a glitch or that the packet got corrupted over the air.  But it isn't.  It reports height=40 every time.  It also reports power as 49.

**Comment by dranch** [comment]
APRS PHG settings like height, power, etc. are not arbitrary.  There are limited, specific options allowed:

   http://aprsisce.wikidot.com/phg

I don't believe this is a bug and if you agree, please close this issue.

**Comment by wcravens** [comment]
Roger, Roger.  I'll close the issue.  This could be good fodder for the documentation though.
