### ISSUE TITLE
Windows (Cygwin / MSYS2) build patch

### ISSUE THREAD

**Issue by srcejon** [wb2osz/direwolf#253]
Hi,

The attach patch gets Direwolf to build on the latest versions of Cygwin/MSYS2 using the ming compilers. (MSYS2 is a bit easier to build with than Cygwin).

[win_patch.txt](https://github.com/wb2osz/direwolf/files/4266584/win_patch.txt)

**Comment by wb2osz** [comment]
Thanks for the suggestion.  As you have probably noticed, the build procedure is entirely different now, using cmake, so this specific patch would no longer apply.  Have you tried using the cmake version?  It works on an amazing variety of platforms, even an IBM system 390 mainframe.  I don't know why you would want to do that but it compiles and runs the self tests.
