### ISSUE TITLE
Empty callsigns in path

### ISSUE THREAD

**Issue by srcejon** [wb2osz/direwolf#254]
Packets received from AISAT appear to have empty callsigns in the path:

[0.2] AISAT-1>CQ,,::CQ-0     :From  AMSAT INDIA & Exseed Space |3264310|39|37|1070{950
APRS Message 950 for "CQ-0", Ambulance
From  AMSAT INDIA & Exseed Space |3264310|39|37|1070{950
[rx>ig] AISAT-1>CQ,,,qAO,M7RCE::CQ-0     :From  AMSAT INDIA & Exseed Space |3264310|39|37|1070{950

[0.2] ON4BN>CQ,AISAT*,::CQ-0     :;AISAT-1  *105428z5000.00N\00400.00WSHi all, on4bn@jubeco.be - JO21{951
APRS Message 951 for "CQ-0"
;AISAT-1  *105428z5000.00N\00400.00WSHi all, on4bn@jubeco.be - JO21{951
[rx>ig] ON4BN>CQ,AISAT*,,qAO,M7RCE::CQ-0     :;AISAT-1  *105428z5000.00N\00400.00WSHi all, on4bn@jubeco.be - JO21{951

Which are then dropped by aprsc igate software, with the error: invalid callsign in path. 

Is this a direwolf problem, or the a problem in the structure of the received packets from AISAT?

**Comment by srcejon** [comment]
I can reproduce this by creating a packet where a via path is "       ". Direwolf just outputs ,,. Perhaps it would be better if it stripped it?

**Comment by srcejon** [comment]
Attached is a possible patch to ax25_pad.c to workaround this:

[ax25_pad_patch.txt](https://github.com/wb2osz/direwolf/files/4266905/ax25_pad_patch.txt)

**Comment by wb2osz** [comment]
The AISAT software was written by someone who did not understand the APRS protocol.  The satellite was obviously launched without testing the APRS software first to see if it was actually compatible with the rest of the world.  It has multiple problems. 

Numerous software developers and countless IGate operators should not be expected to kludge the entire worldwide APRS-IS network to accommodate one faulty implementation of a simple protocol that has been around for decades.   That would only encourage others to be careless and not do any testing.

 Some of the discussion can be found here:

http://lists.tapr.org/pipermail/aprssig_lists.tapr.org/2019-April/047964.html 
http://lists.tapr.org/pipermail/aprssig_lists.tapr.org/2019-April/047994.html
http://lists.tapr.org/pipermail/aprssig_lists.tapr.org/2019-April/047995.html
http://lists.tapr.org/pipermail/aprssig_lists.tapr.org/2019-April/047996.html
http://lists.tapr.org/pipermail/aprssig_lists.tapr.org/2019-April/047997.html
