### ISSUE TITLE
9600 packet decoding failure

### ISSUE THREAD

**Issue by kawks** [wb2osz/direwolf#26]
Here is the recording:
http://tortel.net/~lochner/sunsat/19990303_0225_9600_8bis_22kHz.wav

Direwolf (1.2 release, current master and dev branches) decodes no packets:
```
$ atest -B 9600 19990303_0225_9600_8bis_22kHz.wav 
...
0 packets decoded in 0 seconds.
```
While multimon decodes them fine:
```
$ multimon -q -a FSK9600 -t wav 19990303_0225_9600_8bis_22kHz.wav 
FSK9600: fm SUNSAT-14 to ZS1SUN-14 UI^ pid=F0
......E.!...!.!.E...S....
FSK9600: fm SUNSAT-14 to ZS1SUN-14 UI^ pid=F0
......E.!...!.!.E...S....
FSK9600: fm SUNSAT-14 to ZS1SUN-14 UI^ pid=F0
......E.!...!.!.E...S....
FSK9600: fm SUNSAT-14 to ZS1SUN-14 UI^ pid=F0
......E.!...!.!.E...S....
FSK9600: fm SUNSAT-14 to ZS1SUN-14 UI^ pid=F0
...............AQY!.O.N.N
```

**Comment by wb2osz** [comment]
Try the latest version on the "dev" branch.  Five frames are decoded.

[0] SUNSAT-14>ZS1SUN-14:�<0x03>
[0] SUNSAT-14>ZS1SUN-14:�<0x03>
[0] SUNSAT-14>ZS1SUN-14:�<0x03>
[0] SUNSAT-14>ZS1SUN-14:�<0x03>
[0] SUNSAT-14>ZS1SUN-14:�<0x04><0x01><0x07><0x03>


There is some babbling here discussing minimum audio sample rates vs. data rates for best results:   https://github.com/wb2osz/direwolf/raw/dev/doc/Going-beyond-9600-baud.pdf
