### ISSUE TITLE
Raspberry PI TX issues

### ISSUE THREAD

**Issue by IsaiahKnightVA** [wb2osz/direwolf#264]
I have a Raspberry PI set up with a USB audio card. I created an interface with the Baofeng and built a PTT circuit using a relay connected to a GPIO port.

I am able to receive and decode packets with no problem and have an LED light up for the DCD indicator. But I cannot get it to transmit at all. I even set it to VOX to see if it will transmit and no luck. Any idea why it won't send audio out?

**Comment by dranch** [comment]
Github issues are for bug reports or feature requests only.  Please join the direwolf@groups.io email list and ask your question there.  Please close this issue.

**Comment by IsaiahKnightVA** [comment]
Will do. Sorry.
