### ISSUE TITLE
fsk_fast_filter.h

### ISSUE THREAD

**Issue by videobuff** [wb2osz/direwolf#27]
When compiling from github (or downloading the gz file) on make, i get the error that fsk_fast_filter.h cannot be found.
Right so, because it did not come with the git clone command. I use 

Erik, PA0ESH

Machine: i686
Linux mini-ubuntu 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:26:47 UTC 2016 i686 i686 i686 GNU/Linux

**Comment by wb2osz** [comment]
fsk_fast_filter.h should be generated during the build.  The Makefile rules for it have been cleaned up in the "dev" branch.
