### ISSUE TITLE
gen_packets crashes when stdin input does not contain ':'

### ISSUE THREAD

**Issue by alexandrasandulescu** [wb2osz/direwolf#272]
I tested this issue on Ubuntu 16.04 package, Ubuntu 20.4 package and on master branch. It reproduces on all of them.

Steps to reproduce:
```
echo -n "test" | gen_packets -o x.wav -
```

I discovered this issue when working on [defcon2020 mooodem challenge](https://github.com/o-o-overflow/dc2020q-mooodem-public).

**Comment by wb2osz** [comment]
Now available in dev branch which will eventually become version 1.6,
Thanks for pointing this out.

Good luck in the challenge.

part of commit 0661e23f21344af05e7f014d82e9c6ee118620d7 since I was already in the middle of updating that file.
