### ISSUE TITLE
Pi aprs digipeater

### ISSUE THREAD

**Issue by rgrobinson131** [wb2osz/direwolf#277]
Hi All im trying to build the above following the guide https://godseyonline.net/raspberry-pi-direwolf-digipeater-igate-soundcard-version/
All working apart from I cannot get the auto start to work.. it says in the guide to use
sudo nano /home/pi/.config/lxsession/LXDE-pi/autostart

But it returns with [ Directory '/home/pi/.config/lxsession/LXDE-pi' does not exist ]

I've also tried using crontab-e and adding the line 
* * * * * /home/kp3ft/dw-start.sh >/dev/null 2>&1

And also 
sudo chmod +x dw-start.sh
But when i boot nothing happens. 

Please help.

**Comment by wb2osz** [comment]
The github "issues" section is for reporting software defects ("bugs") or making enhancement requests.
For questions like this, please use the discussion forum. https://groups.io/g/direwolf
