### ISSUE TITLE
Add support for configuring hamlib parameters

### ISSUE THREAD

**Issue by dranch** [wb2osz/direwolf#290]
A user reported that when using Hamlib, it wasn't communicating to their transceiver to key up the radio.  After some troubleshooting, the user found the Direwolf program could successfully communicate to their FT817 radio *if* they configured their radio's CAT port to communicate at 38400 bps.  This class of radio usually defaults at 4800bps.

I feel Direwolf should (at minimum) output what speed it's trying to do CAT PTT control at on STDOUT.  That output will help users clue in to what they need to change on their radio.  On the longer term, setting various "RIG" parameters within direwolf.conf for hamlib parameters should  to be configurable.  A work around could be to use a direwolf.conf rig type "2" and then run rigctld daemon in the background.  That could have all the right settings there but that is a more complex solution.

**Comment by wb2osz** [comment]
Capability has been added to set the serial port speed for hamlib.
Just add it as an optional additional parameter to existing config file commands:

PTT  RIG  model  port [ rate ]
PTT  RIG  AUTO  port [ rate ]

This is in the "dev" branch.
