### ISSUE TITLE
Dev Branch error libgps API version might be incompatible

### ISSUE THREAD

**Issue by Thomas-McCarthy** [wb2osz/direwolf#295]
Seems to be a regression from issue #222

Running on Raspberry Pi 3 Raspberry OS (Linux 5.4.72-v7+ #1356)

When running gpsd version 3.21.1~dev (revision release-3.21-448-g100efd0c3), compiled from source from latest gpsd repo, the following error is displayed when attempting to compile direwolf from the dev branch.

error libgps API version might be incompatible

Editing src/dwgpsd.c and changing the GPSD_API_MAJOR_VERSION value from 10  to 11 appears to solve this.

#if GPSD_API_MAJOR_VERSION < 5 || GPSD_API_MAJOR_VERSION > 11

**Comment by wb2osz** [comment]
Fixed in dev branch 7cd027fcda94307fcf08d0f8ca840b592ccafe9f
