### ISSUE TITLE
Add SOURCE as option for all BEACON commands.

### ISSUE THREAD

**Issue by N7FMH** [wb2osz/direwolf#298]
Primary purpose: allow for a single station to transmit more than one telemetry packet
Ex.
TLMA> T#xxx,val1,val2,val3,val4,val5,fiddlybits
TLMB> T#xxx,val1,val2,val3,val4,val5,fiddlybits

Secondary: allow SOURCE for all beacon options to fix a position to each telemetry position (useful if mobile).
Ex. to assign a location to each telemetry item
TLMA> "location"
TLMB> "location"

Thank you!
N7FMH

**Comment by wb2osz** [comment]
This is now in the 'dev' branch and will be in release 1.7.

**Comment by wb2osz** [comment]
This is now in the 'dev' branch and will be in release 1.7.

**Comment by wb2osz** [comment]
hit the wrong button.

**Comment by N7FMH** [comment]
Very cool! I will install tomorrow!

Thank you!


Best regards, 

Fred N7FMH 


Get Outlook for Android
