### ISSUE TITLE
Makefile.linux

### ISSUE THREAD

**Issue by gregoriosw** [wb2osz/direwolf#3]
Since the moving of the documents to a subdirectory the make file doesn't have the correct directory structure (at least when I did git pull to get the source) to allow the makefile to work.  As I had the documents downloaded I removed the lines with the pdfs from the makefile and also renamed changes.txt to changes.md as that also isn't updated in the makefile.

**Comment by wb2osz** [comment]
The README.md file has been updated with instructions for using git clone.

The "git checkout 1.2" is necessary to get the most recent stable release. The tip of the master branch is temporarily in an inconsistent state during the transition from the old website. If you want the latest (unstable) development version, use "git checkout dev" instead.
