### ISSUE TITLE
Feature requests : SiDS telemetry forwarder.

### ISSUE THREAD

**Issue by rnbokade** [wb2osz/direwolf#318]
Many AX.25 satellites are active in the orbit right now. Direwolf has been used to decode a lot of them along with some kind of external service. Proposal is some app like kissutil that will listen on the kissport and filter the packets with source from notified list if ax.25 satellites. And then automatically forward those to configured SiDS server e.g. Satnogs.

**Comment by dranch** [comment]
Seems like there are already solutions out there to interface Direwolf to SIDS servers:
   https://www.pe0sat.vgnet.nl/decoding/tlm-decoding-software/sids/

Why would you want this to be all within Direwolf?  Direwolf currently is a AX.25/AIS TNC that decodes data and possibly IGATE APRS packets into APRS-IS.  Your ask sounds like it would need to be aware of specific callsigns, etc. and then send to a whole new IGATE-like infrastructure.  Yes?
