### ISSUE TITLE
AGWPE interface does not supply the PATH

### ISSUE THREAD

**Issue by SARTrack** [wb2osz/direwolf#32]
Direwolf:
[AGWE-IN]  1:Fm ZL4FOX-8 To Q7P2U2 <UI pid=F0 Len=36 >[08:25:07]`I1l V>/"9<}[:Barts Tracker 3.83V X

AGWPE:
[AGWE-IN]  1:Fm ZL4FOX-8 To Q7P2U2 Via WIDE3-3 <UI pid=F0 Len=36 >[08:32:14]`I0l V>/"98}[:Barts Tracker 3.83V X

Is this a known issue?
Thanks, Bart

**Comment by wb2osz** [comment]
The digipeater path is now provided.
1.4 Development snapshot C on the "dev" branch.
