### ISSUE TITLE
SATGATE and gating from IS to RF

### ISSUE THREAD

**Issue by mattbk** [wb2osz/direwolf#328]
Should the SATGATE function interfere with gating from IS to RF? Without SATGATE I am transmitting packets from nearby APRS-IS stations to RF, but when I enable SATGATE, no more of these packets are transmitted. 

Dire Wolf version 1.3

**Comment by mattbk** [comment]
I think this can be disregarded. It may depend on the server I was connected to.

**Comment by dranch** [comment]
Please also note that Direwolf v1.3 is VERY old.  If you continue to have issues, please upgrade to Direwolf v1.6 first

**Comment by mattbk** [comment]
Thanks, I figured out my installation issue and have upgraded.
