### ISSUE TITLE
Audio output data underrun in Linux

### ISSUE THREAD

**Issue by minorsecond** [wb2osz/direwolf#360]
When using either Direwolf 1.5 or the latest master in Linux, an audio output data underrun occurs when transmitting. This does not occur in Windows

- OS: Arch Linux
- Rig: FT-818
- Direwolf versions: 1.5, master
- Alsa audio

**Comment by LongnoseRob** [comment]
Hello,

could you provide output from direwolf, ideally with the `-a 10`option set?
Playback of other sounds/music via alsa makes no problems?

**Comment by minorsecond** [comment]
Yes, other audio sources play fine.
I've attached the direwolf output with the `-a 10` flag set.

[direwolf_log.txt](https://github.com/wb2osz/direwolf/files/7570087/direwolf_log.txt)

**Comment by LongnoseRob** [comment]
which sound-hardware are you using?
Have you tried a different sound card?

**Comment by minorsecond** [comment]
It's the XGGCOMS Digimode-4 interface.

I don't have another. An interesting note is that Direwolf was working with this soundcard in Fedora.

**Comment by LongnoseRob** [comment]
have you checked for any messages regarding this interface in dmesg?
have you updated the packages lately?
would you be able to try the dev-branch built from source?

**Comment by minorsecond** [comment]
Nothing from dmesg other than when the device is attached on boot. I'll build the dev branch and test.

**Comment by minorsecond** [comment]
On the latest dev I get the same issue.

**Comment by minorsecond** [comment]
I just tested on the LTS kernel (5.10), and it's working. I'm wondering if they updated the kernel drivers for my audio device between 5.10 and 5.15 and broke it.

**Comment by LongnoseRob** [comment]
@minorsecond Good, atleat know you have a workaround..

**Comment by minorsecond** [comment]
In the meantime, I'm filing a kernel bug report. Thanks for your help!

**Comment by minorsecond** [comment]
The bugzilla report is here, if anyone comes across this issue and wants to follow:

https://bugzilla.kernel.org/show_bug.cgi?id=215073

**Comment by dranch** [comment]
There are still some missing details here that would be good to understand:
   - Which version of Arch Linux is this?  Which specific kernel version were you seeing this issue with?
   - What hardware are you running this on?  X86?  ARM?  If say a Raspberry Pi 3+ or older, you might consider the alternative USB stack to see if that helps

A few more things:  It's highly recommended to run Direwolf v1.6 as it has many fixes over v1.5.  Next, your kernel bug report is incorrect as you are experiencing sound device under runs but your report gave specifics around the FTDI serial device.   http://www.xggcomms.com/userimages/USB-Digimode-4.pdf says this device uses the CM108 sound chipset.  Finally, you might consider putting some ferrites over each cable end of this sound device to potentially avoid any RFI issues.

**Comment by minorsecond** [comment]
Hi dranch,

Arch is rolling release, so there isn't a specific version. Everything matches upstream pretty closely as far as software versions go. The kernel version that doesn't work is 5.15.2. I can reproduce this easily by switching kernels on boot. It works with the 5.10, but not 5.15.

The hardware is an Intel NUC, so it shouldn't be underpowered.

Thanks for the info about the bug report. I'll update it.

**Comment by minorsecond** [comment]
The issue appears to be fixed in kernels 5.15 and 5.16 by adding the following to /etc/modprobe.d/usb-audio.conf and then rebooting:

`echo "options snd-usb-audio lowlatency=n" /etc/modprobe.d/usb-audio.conf`

**Comment by ds2k5** [comment]
could this the same issue in Kernel Version 6.8.0  too ?
