### ISSUE TITLE
Wrong PID text sent to AGWPE client for I frame

### ISSUE THREAD

**Issue by mfncooper** [wb2osz/direwolf#366]
In the mon_desc() function in server.c, the text for the PID is correct for a UI frame but incorrect for an I frame. The latter incorrectly prefixes the PID value with '0x'. 

For example:
    UI frame: "pid=F0"  -- correct
    I frame: "pid=0xF0"  -- incorrect

The comment above the function shows the correct text, per the AGWPE spec, but the code adds the '0x' prefix, such that a client expecting to parse the string per the spec fails.

The bug is here:
https://github.com/wb2osz/direwolf/blob/master/src/server.c#L1035
and the fix is simply to remove the leading '0x' in the format string.

**Comment by wb2osz** [comment]
Fixed in 'dev' branch.
