### ISSUE TITLE
use of non-POSIX __compar_fn_t

### ISSUE THREAD

**Issue by gdt** [wb2osz/direwolf#369]
The source uses __compar_fn_t, which is not specified by POSIX:  https://pubs.opengroup.org/onlinepubs/9699919799/functions/qsort.html 

At least on NetBSD, this is not defined (not a bug, since POSIX doesn't specify it).

An example of how this was addressed in other software is https://pubs.opengroup.org/onlinepubs/9699919799/functions/qsort.html

(Other than this, running cmake and make -k on NetBSD 9, this is the only issue so far -- which is great!)

**Comment by wb2osz** [comment]
I don't see that in the source code anymore in the dev branch.
I guess i fixed it and forgot to close this.
