### ISSUE TITLE
Increase FSK Filter size to support AX.25 9600 baud using 48000 sample rate

### ISSUE THREAD

**Issue by KG6KZZ** [wb2osz/direwolf#413]
Windows 10 required larger FSK filter size to properly support AX.25 9600 baud rate using 48000 audio sample rate to properly run 9600 baud operation.

Increasing to 512 instead of current 417 seemed to solve my problems.

Jason Kim. KG6KZZ

=========================================================
diff --git a/src/fsk_demod_state.h b/src/fsk_demod_state.h
index 33f7901..caf06cd 100644
--- a/src/fsk_demod_state.h
+++ b/src/fsk_demod_state.h
@@ -43,7 +43,8 @@ typedef struct cic_s {
 } cic_t;
 
-#define MAX_FILTER_SIZE 404		/* 401 is needed for profile A, 300 baud & 44100. Revisit someday. */
+#define MAX_FILTER_SIZE 512		/* 417 is needed for profile A, 9600 baud & 48000 Hz. (KG6KZZ). */

 struct demodulator_state_s

**Comment by wb2osz** [comment]
Thank you for reporting this issue and suggesting a fix.
This number was increased to 480 in December 2022.
That seems to be adequate for all cases that I tried.
