### ISSUE TITLE
How does Direwolf control the behavior of DTR ?

### ISSUE THREAD

**Issue by xiaofami** [wb2osz/direwolf#416]
I'm using this interface with a USB soundcard to connect FT-8900R to a TV Box running Manjaro ARM and Direwolf (Version:1.7, built from source )for packet radio :
![1098215657](https://user-images.githubusercontent.com/4654044/181704510-0beba3bf-b331-45e1-9e1e-04ab25a45c9d.jpg)
![1834709778](https://user-images.githubusercontent.com/4654044/181704741-d97a1c77-3bcf-477b-8a64-87eab954b94a.jpg)
![8225994](https://user-images.githubusercontent.com/4654044/181705042-359a4a8a-c8d9-4817-afb6-061ea0d8aa04.jpg)

Currently I'm testing without radio connected. I notice that the **DTR LED** is always on after direwolf is up and running. I'm wondering if it is the expected behavior as the manual of **U5-Link** described : 

    RTS LED: Blink when PTT triggered (Working as expected)
    DTR LED: Blink when CW triggered, synchronized with dot or line (Not working as expected, always on when direwolf running)
    PW LED: ALways on after USB cable is connected (Working as expected)
    REM LED: Blink when changing radio freq with CAT (Could not verify)

I've contact with the U5-Link inventor and he claimed it as "software wrong setting" though I seriously doubt if he has ever played with direwolf. Further more, the manual suggests these setting:

    RTS=PTT
    DTR=CW
    CTS=SQL

so what is supposed to set in direwolf.conf to make DTR behave as expected ?

I only made minimal change to default direwolf and below is what I've changed:

```conf
ADEVICE  plughw:0,0
MYCALL BH2VJW
PTT /dev/ttyUSB0 RTS
```

**Comment by dranch** [comment]
The use of Github "issues" are for reporting bugs and enhancement requests and not for general support.  Please join and repost your issue at direwolf@groups.io and close this issue.  With that said, I encourage you look at using "PTT /dev/ttyUSB0 RTS -DTR"
