### ISSUE TITLE
need CMakeLists.txt for version 1.5

### ISSUE THREAD

**Issue by wf5w** [wb2osz/direwolf#449]
I read somewhere there might be a bug in 1.6 for the problem I am having.

I am on Linux Mint 21, using a digirig [logic levels] ( a CM108  device )

I am in the following groups:
groups=4(adm),5(tty),8(mail),20(dialout),21(fax),24(cdrom),27(sudo),29(audio),30(dip),46(plugdev),112(lpadmin),115(ssh),128(sambashare),131(vboxusers)

from the arecord -l, and using dmesg --follow

I have direwolf.conf appropriately configured as
ADEVICE=plughw:3,0
PTT /dev/ttyUSB0 RTS

When running direwolf -p
I get device or resource busy.

I went into alsamixer, chose my device, changed output to about 40, and mic to about 40 and found out there is also a L R Capture too (which I set to about 40 just to make sure)

Anyway, I stumbled on somebody who said it worked in 1.5 but doesn't in 1.6, so I thought I'd revert to 1.5 and try that out.

So I cloned
Did a $ git reset --hard '1.5'
Did a mkdir build && cd build
Did a cmake .. (no CMakeLists.txt)
So I reverted the head back to current version, copied out the the CMakeLists.txt from there, redid the 1.5, copied the CMakeLists.txt back in. And this time got errors

I would like to test 1.5, so where is the CMakeLists that works with tag 1.5?

Or am I doing this ALL wrong!

Jerry

**Comment by wb2osz** [comment]
Version 1.5 used multiple target specific manually constructed makefiles.
Version 1.6 started using CMake to make multiple platforms easier.

There is no reason to go back to an earlier version that I know of.
You can use the default 1.6 or the "dev" development branch which has many improvements.

There was recently someone using Linux Mint who found out that using a USB3 port was unreliable but a USB2 port was fine.  Watch out for that.

What is the context of the "device or resource busy" error?

**Comment by wb2osz** [comment]
No response from originator for a couple months.  Closing.
