### ISSUE TITLE
Add possibility to define "one" log file name 

### ISSUE THREAD

**Issue by aw-tech** [wb2osz/direwolf#48]
iIt's not issue ;)
Dire Wolf version 1.3
Add possibility to define "one" log file name .
i'm use log file to display data on lcd .. on orangepi.
And need to check directory for new log files.
`//strftime (fname, sizeof(fname), "%Y-%m-%d.log", &tm);`
`strftime (fname, sizeof(fname), direwolf.log", &tm);`
change, in log.c  do the job.,
But it will be cool if we can set up it from command line ,
or maybe i missed something .,
Btw. Great job ...

**Comment by dranch** [comment]
I would agree that log rotation on Linux would be better done with tools like "logrotate" but I don't think Windows has any facility like this.  I wonder if it would be wise to have different configurations for log files depending on the base OS (linux vs. Windows).  I don't know what OSX does here
--David
KI6ZHD

**Comment by bradanlane** [comment]
My solution was to code this as a command line option and/or a CONF file option. The default is to continue to use date-stamped file name.

**Comment by dranch** [comment]
The Direwolf User-Guide.pdf file mentions the LOGDIR directive (not mentioned in the stock direwolf.conf file -- it probably should) but it still uses the yyyy-mm-dd.log format.   Brandan, if you have some code that allows for a .conf / command line, option, could you consider creating a fork, commit your code there, and submit a Git pull back to John for inclusion in Direwolf?  I'm happy to help you do this.. it's not too hard.

**Comment by aw-tech** [comment]
Hi,i made a fork , and add custom log file name , via command line -f.
I'm not programmer , just made some copy and paste..
For example : `sudo direwolf -t 0 -a 100 -d i -l /home/pi/direwolf -f mylog.log`
Without -f , standart log file name with date.
https://github.com/aw-tech/direwolf

**Comment by dranch** [comment]
Ok, your 95% of the way there.  On this new fork you created wit hthe new commit, there is the "pull request" button (not the greatest terminology bit that's what Git calls it).  Click on that button to submit the proposed to John for inclusion in the Dev branch )if he accepts it).

**Comment by aw-tech** [comment]
Ok thanks, i will try.

**Comment by wb2osz** [comment]
Similar functionality is now in the "dev" branch.
52927ce54ab419a67730522d06250569ddf8cf5c
