### ISSUE TITLE
Contributing to Direwolf documentation?

### ISSUE THREAD

**Issue by larsks** [wb2osz/direwolf#485]
I'd like to contribute some changes to the user guide, but I'm not sure where to find the documentation sources. Are they online somewhere? Thanks!

**Comment by wb2osz** [comment]
Only the PDF is published because everyone is able to read it.
You can put minor edits here or e-mail significant changes to  wb2osz <at> arrl <dot> net.
Thanks!

**Comment by larsks** [comment]
Okay, thanks; I'll keep that in mind. It's a shame you don't accept pull requests for the docs.
