### ISSUE TITLE
TOC error in v1.7 User Guide

### ISSUE THREAD

**Issue by mfncooper** [wb2osz/direwolf#492]
The current TOC goes awry after section 9.4, "Radio Channel - Enable IL2P Transmission". The remaining sections (PTT, DCD, etc.) are nested under this Enable IL2P section, instead of being at the same level. That is, we have:

```
9.4  Radio Channel - Enable IL2P Transmission
    9.4.1  Radio Channel - Push to Talk (PTT)
    ...
    9.4.2  Radio Channel - Data Carrier Detect (DCD)
    ...
    etc.
```

instead of:
```
9.4  Radio Channel - Enable IL2P Transmission
9.5  Radio Channel - Push to Talk (PTT)
    ...
9.6  Radio Channel - Data Carrier Detect (DCD)
    ...
    etc.
```

**Comment by wb2osz** [comment]
Thanks for pointing that out.   
Two of the headings should have been at level 3, under radio channel configuration, rather than level 2.
This has been fixed in the draft for the next release.

My tech writer's pay will be cut in half for this mistake.   :-)
