### ISSUE TITLE
Is the 9600bps walkabout9600b.wav recording available anywhere?

### ISSUE THREAD

**Issue by ThomasHabets** [wb2osz/direwolf#502]
Hi. Is the `walkabout9600b.wav` recording mentioned in [this excellent doc](https://github.com/wb2osz/direwolf/blob/master/doc/A-Better-APRS-Packet-Demodulator-Part-2-9600-baud.pdf) available anywhere?

I [made my own](https://blog.habets.se/2023/11/AX.25-and-9600bps-G3RUH-decoding.html), but I suspect that yours is better.

**Comment by wb2osz** [comment]
I tried sending as e-mail attachments.
