### ISSUE TITLE
Unrouted path digipeating?

### ISSUE THREAD

**Issue by sq8vps** [wb2osz/direwolf#51]
Hello.
Is there any way to run the digipeater for unrouted paths?

For example:
Frame transmitted by me:
`SQ8VPS>APRS,SP2-2:info`
And then frame repeated by digi:
`SQ8VPS>APRS,SP2-1:info`
And repeated by next digi:
`SQ8VPS>APRS,SP2*:info`

How can I do that?

73!

**Comment by DL7AD** [comment]
I think there is no option for this. Is this even part of the APRS specification?

Regards Sven

**Comment by sq8vps** [comment]
I don't know, but unrouted paths are used in many countries, for example
SS3-3, SP3-3, HU3-3 etc. Thank you for response.
73!

wt., 23.08.2016, 09:55 użytkownik Sven Steudte <notifications@github.com>
napisał:

**Comment by wb2osz** [comment]
Look in the User Guide, section 9.5.
There is an example which will digipeat the addresses MA3-3, MA2-1, etc.

DIGIPEAT 0 0 ^WIDE[3-7]-[1-7]$ ^WIDE[12]-[12]$|^MA[1-7]-[1-7]$

Take the example above and change MA to SP.

**Comment by sq8vps** [comment]
Thanks for response and your very good app!
73!

śr., 24.08.2016, 03:00 użytkownik wb2osz <notifications@github.com> napisał:
