### ISSUE TITLE
Invalid datakind for Monitor Connected Information in debug_print()

### ISSUE THREAD

**Issue by mfncooper** [wb2osz/direwolf#528]
The AGWPE code for ``debug_print()`` uses the wrong datakind value for Monitor Connected Information in the TO_CLIENT switch statement.

https://github.com/wb2osz/direwolf/blob/dev/src/server.c#L382

The switch uses 'M' whereas the correct value should be 'I'.

This bug is the cause of the "\*\*INVALID\*\*" message types seen in the debug logs posted in issue #497.

**Comment by wb2osz** [comment]
Thank you for pointing out this issue.
This should be resolved in the "dev" branch.
