### ISSUE TITLE
UDP Stream issue

### ISSUE THREAD

**Issue by iz4tow** [wb2osz/direwolf#538]
Good afternoon,
I encountered an issue using UDP device on direwolf

# Scenario
Audio sender: Windows 10 host with ffmpeg

Receiver: Ubuntu Desktop 22.04 with direwolf last release build from github today

## On Windows host (audio sender)
```
ffmpeg -f dshow -i audio="Line 1 (Virtual Audio Cable)" -c 1 -acodec pcm_s16le -b:a 44100 -f mpegts udp://192.168.56.1:12000
```
I tried playing a test.wav generated with gen_packet and tested with atest.

## On Ubuntu
If I try to listen the stream with VLC I can hear it loud and clear, but with direwolf with this command
```
direwolf -n 1 -a 10 -r 44100  udp:12000
```

Output:
```
Dire Wolf version 1.7
Includes optional support for:  hamlib cm108-ptt

Reading config file direwolf.conf
Audio input device for receive: udp:12000  (channel 0)
Audio out device for transmit: null  (channel 0)
Channel 0: Demodulator + option can't be combined with multiple frequencies.
Channel 0: 300 baud, AFSK 1600 & 1800 Hz, A+, 44100 sample rate / 4.
Note: PTT not configured for channel 0. (Ignore this if using VOX.)
Ready to accept AGW client application 0 on port 8000 ...
Ready to accept KISS TCP client application 0 on port 8001 ...

ADEVICE0: Sample rate approx. 10.0 k, 0 errors, receive audio level CH0 195


ADEVICE0: Sample rate approx. 9.8 k, 0 errors, receive audio level CH0 194


ADEVICE0: Sample rate approx. 10.0 k, 0 errors, receive audio level CH0 195


ADEVICE0: Sample rate approx. 10.0 k, 0 errors, receive audio level CH0 194


ADEVICE0: Sample rate approx. 10.0 k, 0 errors, receive audio level CH0 194
```

But...no decoding!

**Comment by dranch** [comment]
A github issue is intended for reporting a bug or requesting a feature, not asking for support.  Instead, please join https://groups.io/g/direwolf and first search the archives for say "udp" and you will find a lot of examples such as https://groups.io/g/direwolf/topic/105984656#msg9570 .  If you still need help, please post your message there and  include the relevant part of of your direwolf.conf file, etc.  Please close this issue unless you strongly believe you have found a bug.
