### ISSUE TITLE
TOCALL ADD:

### ISSUE THREAD

**Issue by richonguzman** [wb2osz/direwolf#542]
Hi,

please add

APLRTx (x from 0 to 9) as LoRa APRS Tracker (from CA2RXU)
APLRGx  (x from 0 to 9) as LoRa APRS iGate (from CA2RXU)

**Comment by dranch** [comment]
Both are present in https://raw.githubusercontent.com/aprsorg/aprs-deviceid/main/generated/tocalls.pretty.json

**Comment by richonguzman** [comment]
ok

this "issue" started as I did not find it here:
https://github.com/wb2osz/direwolf/blob/69407ccf84c443d7da93ef9a63a1ebe7eaf88fce/data/tocalls.txt#L12

but if it loads the data from "tocall.json" file my issue was wrongly started :)

**Comment by wb2osz** [comment]
Earlier versions, including 1.7 (current master branch), used the tocalls.txt file which has not been maintained for a couple years.

The current authority is https://github.com/aprsorg/aprs-deviceid/blob/main/tocalls.yaml  .

The development ("dev") branch, which will become release 1.8, uses tocalls.yaml .

$ grep APL data/tocalls.yaml
...
 - tocall: APLRG?
 - tocall: APLRT?
...

73,
John WB2OSZ

**Comment by richonguzman** [comment]
got it ;)

**Comment by richonguzman** [comment]
hi, i've messaged you on Discord if this does not work can I write you mail?

richonguzman at gmail
