### ISSUE TITLE
Extra 0x00 Added to Packets Sent from AGWPE Client in direwolf(dev)

### ISSUE THREAD

**Issue by jh4xsy** [wb2osz/direwolf#550]
Packets sent from the AGWPE client (UISS) have an added 0x00 in direwolf(dev). 

V1.8D
`[0L 10/17/24 13:39] JH4XSY-1>APRS,DP0SNX:>PM95<0x00>`

This does not occur in direwolf stable.
V1.7
`[0L 10/17/24 13:49] JH4XSY-1>APRS,DP0SNX:>PM95`

**Comment by wb2osz** [comment]
Thank you for reporting this issue.
Fixed in "dev" branch, commit  a83a1ca .

73,
John WB2OSZ
