### ISSUE TITLE
Capture-only audio device not working for a channel. Should it?

### ISSUE THREAD

**Issue by OH2LAK** [wb2osz/direwolf#556]
I'm experimenting with FiFi-SDR devices which feature a capture-only audio device, but apparently Direwolf does not like such devices and gives up as it can not open a playback device for the configured channel.

```
Dec 31 01:58:02 oh2lak-radioserver direwolf[2903]: Audio device for both receive and transmit: plughw:Device,0  (channel 0)
Dec 31 01:58:02 oh2lak-radioserver direwolf[2903]: Audio device for both receive and transmit: plughw:FiFiSDR,1  (channel 2)
Dec 31 01:58:02 oh2lak-radioserver direwolf[2903]: Could not open audio device plughw:FiFiSDR,1 for output
```

As it can be seen in the audio device listing using the 'cm108' -utility, the FiFi-SDR audio device only has the capture device, but no playback device:

```
bofh@oh2lak-radioserver:/tmp# cm108
    VID  PID   Product                          Sound                  ADEVICE        ADEVICE            HID [ptt]
    ---  ---   -------                          -----                  -------        -------            ---------
**  0d8c 013a  USB PnP Sound Device             /dev/snd/pcmC1D0c      plughw:1,0     plughw:Device,0    /dev/hidraw0
**  0d8c 013a  USB PnP Sound Device             /dev/snd/pcmC1D0p      plughw:1,0     plughw:Device,0    /dev/hidraw0
**  0d8c 013a  USB PnP Sound Device             /dev/snd/controlC1                                       /dev/hidraw0
    16c0 05dc  FiFi-SDR                         /dev/snd/pcmC2D0c      plughw:2,0     plughw:FiFiSDR,0
    16c0 05dc  FiFi-SDR                         /dev/snd/pcmC2D1c      plughw:2,1     plughw:FiFiSDR,1
    16c0 05dc  FiFi-SDR                         /dev/snd/controlC2
```

Is there a way to handle such audio device for RX-only channel? Purpose of such is to monitor the 300bps HF APRS packet on 10147,6 kHz USB and 1200bps HF APRS on 29250 kHz FM. FiFi-SDR implements a built-in demodulator making it a perfect RX for such single-frequency use.

Thanks,
Erik OH2LAK

**Comment by wb2osz** [comment]
This is the place to report defects and make enhancement requests.  The discussion forum https://groups.io/g/direwolf/ is for asking questions.  There are many experienced users that can answer this type of question.  The collection of questions and answers can benefit others.

The ADEVICE configuration can have two parameters for different receive audio device and transmit audio device.  For a receive only channel, simply specify null for the transmit audio device like this:

ADEVICE plughw:1,0 null

73,
john WB2OSZ
