### ISSUE TITLE
Missing instructions in Raspberry-Pi-APRS.pdf manual for Automatic Startup

### ISSUE THREAD

**Issue by kq6di** [wb2osz/direwolf#57]
In the Automatic Startup section of the Raspberry-Pi-APRS.pdf manual (section 6.1) it says to add a line into the 'crontab' file to have a script run once a minute.  That portion actually works correctly, but it would not run the script file 'dw-start.sh'.  The script file needs to be flagged as 'executable' for the script to run.  dw-start.sh was not flagged as executable, therefore it did not run.

To make the dw-start.sh file executable, enter :
sudo chmod +x dw-start.sh
at the command prompt.

This is only a documentation issue for this manual.
Arnold
KQ6DI

**Comment by wb2osz** [comment]
The dw-start.sh script has been substantially enhanced.
It should be executable now.
Documentation has been expanded.
