### ISSUE TITLE
"Audio output failure waiting for buffer" 

### ISSUE THREAD

**Issue by cx5cba** [wb2osz/direwolf#78]
![usb audio error](https://cloud.githubusercontent.com/assets/2446136/21949818/03d5866e-d9d4-11e6-9472-77a7fb09c9d7.JPG)

I use a Yaesu FT-991 with the internal USB sound device. Direwolf 1.3.1 Works fine some minutes but in a moment says "Audio output failure waiting for buffer" and don´t work. If restart Direwolf it work fine again. 

regards

Carlos CX5CBA

**Comment by wb2osz** [comment]
This is more than 3 years old.  Please reopen case if still a problem in more recent version.  Thanks.
