### ISSUE TITLE
The telemetry toolkit would benefit from a simple way to increase sequence numbers

### ISSUE THREAD

**Issue by elafargue** [wb2osz/direwolf#9]
Some services (aprs.fi for instance) will complain about duplicate sequence numbers for telemetry if the sequence number is not changed at each packet...

**Comment by elafargue** [comment]
I used the following little script in my CBEACON commands, I'm sure it's possible to compress it as a one-liner though:

    #!/bin/sh
    SEQ=`cat /tmp/seq`
    SEQ=$(expr \( $SEQ + 1 \) % 100)
    echo $SEQ | tee /tmp/seq

**Comment by wb2osz** [comment]
A new script, telem-seq.sh, has been added.
This has been pushed to the "dev" branch.
