### ISSUE TITLE
Axspawn

### ISSUE THREAD

**Issue by felixdube** [wb2osz/direwolf#90]
Hi there,

I have notice an issue when using Direwolf along with Axspawn. Here is my setup. I have two computers communicating over an AX.25 link using Direwolf 1.3. There is one computer, GND0, connecting to the other computer, SAT0, using Axspawn.

The issue is when SAT0 tries to send something "big" to GND0 only part of the message is being sent.

Here is an example. When GND0 does "ls" in some folder, SAT0 does answer properly.
Screenshot from GND0:
![screenshot from 2017-03-18 08-53-19](https://cloud.githubusercontent.com/assets/5619631/24076929/bd47cca8-0c13-11e7-9517-9a1f2c9d37c7.png)
![screenshot from 2017-03-18 08-53-42](https://cloud.githubusercontent.com/assets/5619631/24076935/db907228-0c13-11e7-928c-15114273b31a.png)

Screenshot from SAT0:
<img width="1101" alt="screen shot 2017-03-18 at 8 54 09 am" src="https://cloud.githubusercontent.com/assets/5619631/24076928/a685f382-0c13-11e7-94d2-7e0916d5f6d1.png">

However, when GND0  does "ls -l", only part of what should be sent is being sent.
Screenshot from GND0:
![screenshot from 2017-03-18 08-54-54](https://cloud.githubusercontent.com/assets/5619631/24076938/def9cf68-0c13-11e7-9aeb-cb6b21790494.png)
![screenshot from 2017-03-18 08-55-24](https://cloud.githubusercontent.com/assets/5619631/24076939/e11ff5ba-0c13-11e7-91bd-b48dae418dad.png)

Screenshot from SAT0:
<img width="1106" alt="screen shot 2017-03-18 at 8 54 30 am" src="https://cloud.githubusercontent.com/assets/5619631/24076926/a09d4e84-0c13-11e7-94a2-7bdb16cce9ea.png">

This is what I expect when doing "ls -l":
<img width="573" alt="screen shot 2017-03-18 at 7 49 53 pm" src="https://cloud.githubusercontent.com/assets/5619631/24076947/1da3078e-0c14-11e7-8c91-0680e3821314.png">

Thank you, keep up the great work!!

**Comment by dranch** [comment]
This could be an axspawn issue but I see no issue with Direwolf here.  I can propose some ideas for further troubleshooting in the Direwolf support email list but please close this issue as it's out of scope for Direwolf.

**Comment by felixdube** [comment]
What is the support email list?

Thank you!!

**Comment by dranch** [comment]
direwolf_packet@yahoogroups.com

**Comment by dranch** [comment]
More than you asked but:

The direwolf email support list is is focused on Direwolf and AX.25 issues and can be found at direwolf_packet@yahoogroups.com.  For a serious brain trust of Linux AX.25 users with advanced topics like yours, consider joining the 44net@hamradio.ucsd.edu list.  Though your issue isn't AMPR 44.x.x.x related, I'm SURE someone there will have a thought on your strange issue.  Also consider the Raspberry_Pi_4-Ham_RADIO@yahoogroups.com (if running on an RPI) list as it's quite active.  There is also the  linuxham@groups.io which is a list more focused on Fldigi and it's suite of programs but they support and encourage other Linux + Hamradio application support questions there.  Finally, for more Linux AX.25 kernel centric issues, consider linux-hams@vger.kernel.org (but it's very low traffic these days).  It's really more for reporting and posting fixes for ax.25 kernel issues.

**Comment by felixdube** [comment]
Thank you so much for your fast response!!
