### ISSUE TITLE
Dual rtl usb devices?

### ISSUE THREAD

**Issue by vaderj** [wb2osz/direwolf#95]
I'm sorry if this has already been addressed, but I have been searching for a couple days for how to tell Direwolf with RTL device to use when multiple RTL devices are present.  I am attempting to run direwolf and PiAware concurrently on the same RasPi

**Comment by dranch** [comment]
The "issues" area is for Direwolf issues or enhancement requests.  Please close this "issue", join the Direwolf Yahoo email list at direwolf_packet@yahoogroups.com, and ask your question there.  Ultimately, you'll want to use rtl_fm's "-d" option to use one RTL device per Direwolf instance.
