### ISSUE TITLE
KISS port accepts only one connection

### ISSUE THREAD

**Issue by regulatre** [wb2osz/direwolf#96]
From what I can tell, I can connect to the KISS port (KISSPORT 8001) but after I disconnect from the KISS port and try to reconnect, connection is refused. It seems Direwolf only accepts a single inbound connection and when that connection closes, no further connections may be made to Direwolf (without restarting direwolf).

**Comment by na7q** [comment]
If you're in windows then this is the expected behavior. Linux supports multiple connections at a time. Windows does not. If you are using Linux and having this problem, I'm curious about, as I use multiple KISS connections at any given time, no issues.

**Comment by nytowl** [comment]
I wrote a patch that will allow multiple connections , just waiting on the merge request now.

**Comment by wb2osz** [comment]
Please try the version on the "dev" branch (1.5 dev A) and see if it is working ok.

**Comment by wb2osz** [comment]
Please try the version on the "dev" branch (1.5 dev A) and see if it is working ok.
