### ISSUE TITLE
Compiler Warnings under GCC V7.1 and Fedora 26

### ISSUE THREAD

**Issue by DwaineGarden** [wb2osz/direwolf#99]
Just posting some of the GCC v7.1 warnings from a compile.

make -j4
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o direwolf.o direwolf.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o config.o config.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o recv.o recv.c
echo " " > tune.h
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD -DGEN_FFF -o gen_fff demod_afsk.c dsp.c textcolor.c -lm -lpthread -lrt -lasound -lgps
echo " " > tune.h
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o dsp.o dsp.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o demod_psk.o demod_psk.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o demod_9600.o demod_9600.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o hdlc_rec.o hdlc_rec.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o hdlc_rec2.o hdlc_rec2.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o multi_modem.o multi_modem.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o rdq.o rdq.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o rrbb.o rrbb.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o dlq.o dlq.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o fcs_calc.o fcs_calc.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o ax25_pad.o ax25_pad.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o ax25_pad2.o ax25_pad2.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o xid.o xid.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o decode_aprs.o decode_aprs.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o symbols.o symbols.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o server.o server.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o kiss.o kiss.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o kissserial.o kissserial.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o kissnet.o kissnet.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o kiss_frame.o kiss_frame.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o hdlc_send.o hdlc_send.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o gen_tone.o gen_tone.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o audio.o audio.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o audio_stats.o audio_stats.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o digipeater.o digipeater.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o cdigipeater.o cdigipeater.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o pfilter.o pfilter.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o dedupe.o dedupe.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o tq.o tq.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o xmit.o xmit.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o morse.o morse.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o ptt.o ptt.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o beacon.o beacon.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o encode_aprs.o encode_aprs.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o latlong.o latlong.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o textcolor.o textcolor.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o dtmf.o dtmf.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o aprs_tt.o aprs_tt.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o tt_user.o tt_user.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o tt_text.o tt_text.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o igate.o igate.c
tt_text.c: In function ‘tt_text_to_call10’:
tt_text.c:542:35: warning: ‘%04d’ directive output may be truncated writing between 4 and 10 bytes into a region of size 8 [-Wformat-truncation=]
  snprintf (stemp, sizeof(stemp), "%04d", packed);
                                   ^~~~
tt_text.c:542:34: note: directive argument in the range [0, 2147483647]
  snprintf (stemp, sizeof(stemp), "%04d", packed);
                                  ^~~~~~
tt_text.c:542:2: note: ‘snprintf’ output between 5 and 11 bytes into a destination of size 8
  snprintf (stemp, sizeof(stemp), "%04d", packed);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o waypoint.o waypoint.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o serial_port.o serial_port.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o log.o log.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o telemetry.o telemetry.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o dwgps.o dwgps.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o dwgpsnmea.o dwgpsnmea.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o dwgpsd.o dwgpsd.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o dtime_now.o dtime_now.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o mheard.o mheard.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o ax25_link.o ax25_link.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD -I. -c -o strlcpy.o misc/strlcpy.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD -I. -c -o strlcat.o misc/strlcat.c
mheard.c: In function ‘mheard_dump’:
mheard.c:210:24: warning: ‘%02d’ directive writing between 2 and 9 bytes into a region of size between 8 and 11 [-Wformat-overflow=]
  sprintf (result, "%4d:%02d", h, m);
                        ^~~~
mheard.c:210:19: note: directive argument in the range [-71582774, 71582774]
  sprintf (result, "%4d:%02d", h, m);
                   ^~~~~~~~~~
mheard.c:210:2: note: ‘sprintf’ output between 8 and 18 bytes into a destination of size 16
  sprintf (result, "%4d:%02d", h, m);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mheard.c:210:24: warning: ‘%02d’ directive writing between 2 and 9 bytes into a region of size between 8 and 11 [-Wformat-overflow=]
  sprintf (result, "%4d:%02d", h, m);
                        ^~~~
mheard.c:210:19: note: directive argument in the range [-71582774, 71582774]
  sprintf (result, "%4d:%02d", h, m);
                   ^~~~~~~~~~
mheard.c:210:2: note: ‘sprintf’ output between 8 and 18 bytes into a destination of size 16
  sprintf (result, "%4d:%02d", h, m);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD -c -o error_string.o geotranz/error_string.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD -c -o mgrs.o geotranz/mgrs.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD -c -o polarst.o geotranz/polarst.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD -c -o tranmerc.o geotranz/tranmerc.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD -c -o ups.o geotranz/ups.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD -c -o usng.o geotranz/usng.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD -c -o utm.o geotranz/utm.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o ttcalc.o ttcalc.c
Generating customized direwolf.desktop ...
./gen_fff > fsk_fast_filter.h
ar -cr misc.a strlcpy.o strlcat.o	
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o demod.o demod.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD   -c -o demod_afsk.o demod_afsk.c
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD -DDECAMAIN -o decode_aprs decode_aprs.c dwgpsnmea.o dwgps.o dwgpsd.o serial_port.o symbols.o ax25_pad.o textcolor.o fcs_calc.o latlong.o log.o telemetry.o tt_text.o misc.a -lm -lpthread -lrt -lasound -lgps
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD -DENC_MAIN -o text2tt tt_text.c misc.a -lm -lpthread -lrt -lasound -lgps
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD -DDEC_MAIN -o tt2text tt_text.c misc.a -lm -lpthread -lrt -lasound -lgps
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD -g -o aclients aclients.c ax25_pad.c fcs_calc.c textcolor.o misc.a 
tt_text.c: In function ‘tt_text_to_call10’:
tt_text.c:542:35: warning: ‘%04d’ directive output may be truncated writing between 4 and 10 bytes into a region of size 8 [-Wformat-truncation=]
  snprintf (stemp, sizeof(stemp), "%04d", packed);
                                   ^~~~
tt_text.c:542:34: note: directive argument in the range [0, 2147483647]
  snprintf (stemp, sizeof(stemp), "%04d", packed);
                                  ^~~~~~
tt_text.c:542:2: note: ‘snprintf’ output between 5 and 11 bytes into a destination of size 8
  snprintf (stemp, sizeof(stemp), "%04d", packed);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tt_text.c: In function ‘tt_text_to_call10’:
tt_text.c:542:35: warning: ‘%04d’ directive output may be truncated writing between 4 and 10 bytes into a region of size 8 [-Wformat-truncation=]
  snprintf (stemp, sizeof(stemp), "%04d", packed);
                                   ^~~~
tt_text.c:542:34: note: directive argument in the range [0, 2147483647]
  snprintf (stemp, sizeof(stemp), "%04d", packed);
                                  ^~~~~~
tt_text.c:542:2: note: ‘snprintf’ output between 5 and 11 bytes into a destination of size 8
  snprintf (stemp, sizeof(stemp), "%04d", packed);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD -o atest atest.c demod.o demod_afsk.o demod_psk.o demod_9600.o dsp.o hdlc_rec.o hdlc_rec2.o multi_modem.o rrbb.o fcs_calc.o ax25_pad.o decode_aprs.o dwgpsnmea.o dwgps.o dwgpsd.o serial_port.o telemetry.o dtime_now.o latlong.o symbols.o tt_text.o textcolor.o misc.a -lm -lpthread -lrt -lasound -lgps
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD -o log2gpx log2gpx.c textcolor.o misc.a -lm -lpthread -lrt -lasound -lgps
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD -o gen_packets gen_packets.c ax25_pad.c hdlc_send.c fcs_calc.c gen_tone.c morse.c dtmf.c textcolor.c dsp.c misc.a -lm -lpthread -lrt -lasound -lgps
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD -g -o ttcalc ttcalc.o ax25_pad.o fcs_calc.o textcolor.o misc.a 
gen_packets.c: In function ‘main’:
gen_packets.c:647:38: warning: ‘snprintf’ output may be truncated before the last format character [-Wformat-truncation=]
      snprintf (stemp, sizeof(stemp), "WB2OSZ-15>TEST:,The quick brown fox jumps over the lazy dog!  %04d of %04d", i, packet_count);
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gen_packets.c:647:6: note: ‘snprintf’ output between 75 and 88 bytes into a destination of size 80
      snprintf (stemp, sizeof(stemp), "WB2OSZ-15>TEST:,The quick brown fox jumps over the lazy dog!  %04d of %04d", i, packet_count);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ar -cr geotranz.a error_string.o mgrs.o polarst.o tranmerc.o ups.o usng.o utm.o
gcc -o direwolf direwolf.o config.o recv.o demod.o dsp.o demod_afsk.o demod_psk.o demod_9600.o hdlc_rec.o hdlc_rec2.o multi_modem.o rdq.o rrbb.o dlq.o fcs_calc.o ax25_pad.o ax25_pad2.o xid.o decode_aprs.o symbols.o server.o kiss.o kissserial.o kissnet.o kiss_frame.o hdlc_send.o gen_tone.o audio.o audio_stats.o digipeater.o cdigipeater.o pfilter.o dedupe.o tq.o xmit.o morse.o ptt.o beacon.o encode_aprs.o latlong.o textcolor.o dtmf.o aprs_tt.o tt_user.o tt_text.o igate.o waypoint.o serial_port.o log.o telemetry.o dwgps.o dwgpsnmea.o dwgpsd.o dtime_now.o mheard.o ax25_link.o misc.a geotranz.a -lm -lpthread -lrt -lasound -lgps
 
This includes support for gpsd.
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD -o ll2utm ll2utm.c geotranz.a textcolor.o misc.a -lm -lpthread -lrt -lasound -lgps
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA -DENABLE_GPSD -o utm2ll utm2ll.c geotranz.a textcolor.o misc.a -lm -lpthread -lrt -lasound -lgps
 
Next step - install with:
 
        sudo make install

**Comment by dranch** [comment]
Hello Dwaine,
Can you tell us what Linux distribution this is on?

**Comment by DwaineGarden** [comment]
Red Hat Fedora 26

**Comment by DwaineGarden** [comment]
GCC 7.1.1

**Comment by DwaineGarden** [comment]
Did a push for two fixes to the warnings...

**Comment by wb2osz** [comment]
Fixed.
Thanks for pointing this out.
